global:
  scrape_interval: 10s
  evaluation_interval: 10s

alerting:
  alertmanagers:
  - static_configs:
    - targets:

rule_files:

scrape_configs:
  - job_name: 'app'
    static_configs:
      - targets: [ 'app:80' ]
