{
 "title": "app monitoring",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count[1m]))",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "http errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{status_code=~\"5..\"}[1m]))",
     "legendFormat": "5xx"
    },
    {
     "expr": "sum(increase(http_request_duration_seconds_count{status_code=~\"4..\"}[1m]))",
     "legendFormat": "4xx"
    }
   ]
  },
  {
   "title": "latency (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "1000 * (sum(rate(http_request_duration_seconds_sum[1m])) / sum(rate(http_request_duration_seconds_count[1m])))",
     "legendFormat": "latency (ms)"
    }
   ]
  },
  {
   "title": "new tweets collected",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "increase(tweets_total[10m])", "legendFormat": "new tweets" }
   ]
  },
  {
   "title": "log lines by level",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({service=\"latest-tweets-sample\"}[$__interval])) by (level)"
    }
   ]
  },
  {
   "title": "tweets collects by status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(cron_runs_count{status=\"error\"}[10m])",
     "legendFormat": "error"
    },
    {
     "expr": "increase(cron_runs_count{status=\"sucess\"}[10m])",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "log lines",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{service=\"latest-tweets-sample\"}"
    }
   ]
  }
 ]
}